/*
 * This source file was generated by the Gradle 'init' task
 */
package de.pottgames.videocompressor;

import atlantafx.base.theme.Dracula;
import atlantafx.base.theme.Styles;
import de.pottgames.videocompressor.view.StepView;
import de.pottgames.videocompressor.view.step.Step1View;
import de.pottgames.videocompressor.view.step.Step2View;
import de.pottgames.videocompressor.view.step.Step3View;
import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Line;
import javafx.stage.Stage;

public class App extends Application {

    private StepView currentStep;

    private Step1View step1View;
    private Step2View step2View;
    private Step3View step3View;

    private Button backButton;
    private Button centerButton;
    private Button nextButton;
    private BorderPane root;

    @Override
    public void start(Stage stage) {
        Application.setUserAgentStylesheet(
            new Dracula().getUserAgentStylesheet()
        );

        // Initialize step views
        step1View = new Step1View();
        step2View = new Step2View();
        step3View = new Step3View();

        // Initialize the root layout
        root = new BorderPane();
        root.setPadding(new Insets(0));

        // Create navigation buttons
        backButton = createNavigationButton("← Zurück", false);
        centerButton = createNavigationButton("", false);
        nextButton = createNavigationButton("Weiter →", true);

        // Create stepper progress indicator
        HBox stepper = createStepper();
        root.setTop(stepper);

        // Create bottom navigation bar
        BorderPane navBar = createNavBar();
        root.setBottom(navBar);

        switchStep(null, false);

        Scene scene = new Scene(root, 900, 650);
        stage.setTitle("VideoCompressor");
        stage.setScene(scene);
        stage.show();
    }

    private Button createNavigationButton(String text, boolean primary) {
        Button button = new Button(text);
        button.setMinWidth(160);
        button.setMaxWidth(200);
        button.setPadding(new Insets(10, 16, 10, 16));

        if (primary) {
            button.setStyle("-fx-cursor: hand;");
            button.getStyleClass().add(Styles.ACCENT);
            button.setOnMouseEntered(e -> button.setStyle("-fx-cursor: hand;"));
            button.setOnMouseExited(e -> button.setStyle("-fx-cursor: hand;"));
        } else {
            button.setStyle("-fx-cursor: hand;");
            button.setOnMouseEntered(e -> button.setStyle("-fx-cursor: hand;"));
            button.setOnMouseExited(e -> button.setStyle("-fx-cursor: hand;"));
        }

        return button;
    }

    private BorderPane createNavBar() {
        BorderPane navBar = new BorderPane();
        navBar.setPadding(new Insets(16, 20, 16, 20));
        navBar.setLeft(backButton);
        navBar.setCenter(centerButton);
        navBar.setRight(nextButton);

        // Button click handlers
        backButton.setOnAction(e -> switchStep(currentStep, true));
        nextButton.setOnAction(e -> switchStep(currentStep, false));

        return navBar;
    }

    private void switchStep(StepView fromStep, boolean goBack) {
        StepView nextStep;

        if (fromStep == step1View) {
            nextStep = goBack ? step1View : step2View;
        } else if (fromStep == step2View) {
            nextStep = goBack ? step1View : step3View;
        } else if (fromStep == step3View) {
            nextStep = goBack ? step2View : step3View;
        } else {
            nextStep = step1View;
        }

        if (nextStep != fromStep) {
            if (fromStep != null) fromStep.deactivate();
            this.root.setCenter(nextStep.getNode());
            currentStep = nextStep;
            nextStep.activate(backButton, centerButton, nextButton);
        }
    }

    private HBox createStepper() {
        HBox stepper = new HBox();
        stepper.setPadding(new Insets(15, 20, 15, 20));
        stepper.setAlignment(Pos.CENTER);
        stepper.setSpacing(0);

        // Step 1: Import
        Circle step1Ring = new Circle(18);
        step1Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step1Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step1Ring.setStrokeWidth(3);

        Label step1Number = new Label("1");
        step1Number.setStyle(
            "-fx-text-fill: #9580FFFF; -fx-font-size: 18px; -fx-font-weight: bold;"
        );

        StackPane step1NumberPane = new StackPane(step1Ring, step1Number);
        step1NumberPane.setAlignment(Pos.CENTER);

        Label step1Label = new Label("Import");
        step1Label.setStyle(
            "-fx-text-fill: #f8f8f2; -fx-font-size: 13px; -fx-font-weight: bold;"
        );

        VBox step1Box = new VBox(8, step1NumberPane, step1Label);
        step1Box.setAlignment(Pos.CENTER);

        // Line 1-2
        Line line1 = new Line(0, 18, 300, 18);
        line1.setStroke(javafx.scene.paint.Color.web("#6272a4"));
        line1.setStrokeWidth(3);

        // Step 2: Einstellungen
        Circle step2Ring = new Circle(18);
        step2Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step2Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step2Ring.setStrokeWidth(3);

        Label step2Number = new Label("2");
        step2Number.setStyle(
            "-fx-text-fill: #9580FFFF; -fx-font-size: 18px; -fx-font-weight: bold;"
        );

        StackPane step2NumberPane = new StackPane(step2Ring, step2Number);
        step2NumberPane.setAlignment(Pos.CENTER);

        Label step2Label = new Label("Einstellungen");
        step2Label.setStyle(
            "-fx-text-fill: #f8f8f2; -fx-font-size: 13px; -fx-font-weight: bold;"
        );

        VBox step2Box = new VBox(8, step2NumberPane, step2Label);
        step2Box.setAlignment(Pos.CENTER);

        // Line 2-3
        Line line2 = new Line(0, 18, 300, 18);
        line2.setStroke(javafx.scene.paint.Color.web("#6272a4"));
        line2.setStrokeWidth(3);

        // Step 3: Export
        Circle step3Ring = new Circle(18);
        step3Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step3Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step3Ring.setStrokeWidth(3);

        Label step3Number = new Label("3");
        step3Number.setStyle(
            "-fx-text-fill: #9580FFFF; -fx-font-size: 18px; -fx-font-weight: bold;"
        );

        StackPane step3NumberPane = new StackPane(step3Ring, step3Number);
        step3NumberPane.setAlignment(Pos.CENTER);

        Label step3Label = new Label("Export");
        step3Label.setStyle(
            "-fx-text-fill: #f8f8f2; -fx-font-size: 13px; -fx-font-weight: bold;"
        );

        VBox step3Box = new VBox(8, step3NumberPane, step3Label);
        step3Box.setAlignment(Pos.CENTER);

        // Add minimal horizontal padding between lines and circles
        HBox.setMargin(line1, new Insets(0, 8, 0, 16));
        HBox.setMargin(line2, new Insets(0, 16, 0, 8));

        stepper
            .getChildren()
            .addAll(step1Box, line1, step2Box, line2, step3Box);

        return stepper;
    }

    public static void main(String[] args) {
        launch(args);
    }
}
