/*
 * This source file was generated by the Gradle 'init' task
 */
package de.pottgames.videocompressor;

import atlantafx.base.theme.Dracula;
import atlantafx.base.theme.Styles;
import de.pottgames.videocompressor.view.StepView;
import de.pottgames.videocompressor.view.step.Step1View;
import de.pottgames.videocompressor.view.step.Step2View;
import de.pottgames.videocompressor.view.step.Step3View;
import java.io.File;
import javafx.application.Application;
import javafx.collections.ListChangeListener;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {

    private StepView currentStep;

    private Step1View step1View;
    private Step2View step2View;
    private Step3View step3View;

    private Button backButton;
    private Button centerButton;
    private Button nextButton;
    private BorderPane root;

    @Override
    public void start(Stage stage) {
        Application.setUserAgentStylesheet(
            new Dracula().getUserAgentStylesheet()
        );

        // Initialize step views
        step1View = new Step1View();
        step2View = new Step2View();
        step3View = new Step3View();

        // Initialize the root layout
        root = new BorderPane();
        root.setPadding(new Insets(0));

        // Create navigation buttons
        backButton = createNavigationButton("← Zurück", false);
        centerButton = createNavigationButton("", false);
        nextButton = createNavigationButton("Weiter →", true);

        // Create bottom navigation bar
        BorderPane navBar = createNavBar();
        root.setBottom(navBar);

        switchStep(null, false);

        Scene scene = new Scene(root, 900, 650);
        stage.setTitle("VideoCompressor");
        stage.setScene(scene);
        stage.show();
    }

    private Button createNavigationButton(String text, boolean primary) {
        Button button = new Button(text);
        button.setMinWidth(160);
        button.setMaxWidth(200);
        button.setPadding(new Insets(10, 16, 10, 16));

        if (primary) {
            button.setStyle("-fx-cursor: hand;");
            button.getStyleClass().add(Styles.ACCENT);
            button.setOnMouseEntered(e -> button.setStyle("-fx-cursor: hand;"));
            button.setOnMouseExited(e -> button.setStyle("-fx-cursor: hand;"));
        } else {
            button.setStyle("-fx-cursor: hand;");
            button.setOnMouseEntered(e -> button.setStyle("-fx-cursor: hand;"));
            button.setOnMouseExited(e -> button.setStyle("-fx-cursor: hand;"));
        }

        return button;
    }

    private BorderPane createNavBar() {
        BorderPane navBar = new BorderPane();
        navBar.setPadding(new Insets(16, 20, 16, 20));
        navBar.setLeft(backButton);
        navBar.setCenter(centerButton);
        navBar.setRight(nextButton);

        // Button click handlers
        backButton.setOnAction(e -> switchStep(currentStep, true));
        nextButton.setOnAction(e -> switchStep(currentStep, false));

        return navBar;
    }

    private void switchStep(StepView fromStep, boolean goBack) {
        StepView nextStep;

        if (fromStep == step1View) {
            nextStep = goBack ? step1View : step2View;
        } else if (fromStep == step2View) {
            nextStep = goBack ? step1View : step3View;
        } else if (fromStep == step3View) {
            nextStep = goBack ? step2View : step3View;
        } else {
            nextStep = step1View;
        }

        if (nextStep != fromStep) {
            if (fromStep != null) fromStep.deactivate();
            this.root.setCenter(nextStep.getNode());
            currentStep = nextStep;
            nextStep.activate(backButton, centerButton, nextButton);
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
