/*
 * This source file was generated by the Gradle 'init' task
 */
package de.pottgames.videocompressor;

import atlantafx.base.theme.Dracula;
import atlantafx.base.theme.Styles;
import de.pottgames.videocompressor.engine.Engine;
import de.pottgames.videocompressor.view.StepView;
import de.pottgames.videocompressor.view.step.Step1View;
import de.pottgames.videocompressor.view.step.Step2View;
import de.pottgames.videocompressor.view.step.Step3View;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.HBox;
import javafx.scene.layout.StackPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Circle;
import javafx.scene.shape.Line;
import javafx.stage.Stage;

public class App extends Application {

    // Window size
    private static final int WINDOW_WIDTH = 900;
    private static final int WINDOW_HEIGHT = 700;

    private StepView currentStep;

    private Step1View step1View;
    private Step2View step2View;
    private Step3View step3View;

    // Engine instance (initialized asynchronously at startup)
    private Engine engine;

    private Button backButton;
    private Button centerButton;
    private Button nextButton;
    private BorderPane root;

    // Stepper UI elements
    private Circle step1Ring;
    private Label step1Number;
    private Label step1Label;
    private Circle step2Ring;
    private Label step2Number;
    private Label step2Label;
    private Circle step3Ring;
    private Label step3Number;
    private Label step3Label;
    private Line line1;
    private Line line2;

    // Active step index (1, 2, or 3)
    private int activeStep = 1;

    @Override
    public void start(Stage stage) {
        System.out.println(
            "Current working directory: " + System.getProperty("user.dir")
        );

        Application.setUserAgentStylesheet(
            new Dracula().getUserAgentStylesheet()
        );

        // Initialize step views
        step1View = new Step1View();
        step2View = new Step2View();
        step3View = new Step3View();

        // Asynchronously initialize the engine (loads presets, validates FFMPEG, etc.)
        Engine.initialize().thenAccept(engine -> {
            this.engine = engine;
            // Update Step2View with loaded presets on the JavaFX Application Thread
            Platform.runLater(() -> step2View.setEngine(engine));
        });

        // Initialize the root layout
        root = new BorderPane();
        root.setPadding(new Insets(0));

        // Create navigation buttons
        backButton = createNavigationButton("← Zurück", false);
        centerButton = createNavigationButton("", false);
        nextButton = createNavigationButton("Weiter →", true);

        // Create stepper progress indicator
        HBox stepper = createStepper();
        root.setTop(stepper);

        // Create bottom navigation bar
        BorderPane navBar = createNavBar();
        root.setBottom(navBar);

        switchStep(null, false);

        Scene scene = new Scene(root, WINDOW_WIDTH, WINDOW_HEIGHT);
        stage.setTitle("VideoCompressor");
        stage.setScene(scene);
        stage.setMinWidth(WINDOW_WIDTH);
        stage.setMinHeight(WINDOW_HEIGHT);
        stage.show();
    }

    private Button createNavigationButton(String text, boolean primary) {
        Button button = new Button(text);
        button.setMinWidth(200);
        button.setMaxWidth(200);
        button.setPadding(new Insets(10, 16, 10, 16));

        if (primary) {
            button.getStyleClass().addAll(Styles.ACCENT);
        }
        button.setStyle("-fx-cursor: hand;");

        return button;
    }

    private BorderPane createNavBar() {
        BorderPane navBar = new BorderPane();
        navBar.setPadding(new Insets(16, 20, 16, 20));
        navBar.setLeft(backButton);
        navBar.setCenter(centerButton);
        navBar.setRight(nextButton);

        // Button click handlers
        backButton.setOnAction(_ -> switchStep(currentStep, true));
        nextButton.setOnAction(_ -> switchStep(currentStep, false));

        return navBar;
    }

    private void switchStep(StepView fromStep, boolean goBack) {
        StepView nextStep;

        if (fromStep == step1View) {
            nextStep = goBack ? step1View : step2View;
        } else if (fromStep == step2View) {
            nextStep = goBack ? step1View : step3View;
        } else if (fromStep == step3View) {
            nextStep = goBack ? step2View : step3View;
        } else {
            nextStep = step1View;
        }

        if (nextStep != fromStep) {
            if (fromStep != null) fromStep.deactivate();
            this.root.setCenter(nextStep.getNode());
            currentStep = nextStep;
            nextStep.activate(backButton, centerButton, nextButton);

            // Update active step for stepper indicator
            if (nextStep == step1View) {
                activeStep = 1;
            } else if (nextStep == step2View) {
                activeStep = 2;
            } else if (nextStep == step3View) {
                activeStep = 3;
            }
            updateStepperState();
        }
    }

    private HBox createStepper() {
        HBox stepper = new HBox();
        stepper.setPadding(new Insets(15, 20, 15, 20));
        stepper.setAlignment(Pos.CENTER);
        stepper.setSpacing(0);

        // Step 1: Import
        step1Ring = new Circle(18);
        step1Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step1Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step1Ring.setStrokeWidth(3);

        step1Number = new Label("1");
        step1Number.setStyle("-fx-text-fill: #9580FFFF; -fx-font-size: 20px;");
        step1Number.getStyleClass().addAll(Styles.TEXT_BOLD);

        StackPane step1NumberPane = new StackPane(step1Ring, step1Number);
        step1NumberPane.setAlignment(Pos.CENTER);

        step1Label = new Label("Import");
        step1Label.setStyle("-fx-text-fill: #f8f8f2; -fx-font-size: 16px;");
        step1Label.getStyleClass().addAll(Styles.TEXT_BOLD);

        VBox step1Box = new VBox(8, step1NumberPane, step1Label);
        step1Box.setAlignment(Pos.CENTER);

        // Line 1-2
        line1 = new Line(0, 18, 300, 18);
        line1.setStroke(javafx.scene.paint.Color.web("#6272a4"));
        line1.setStrokeWidth(3);

        // Step 2: Einstellungen
        step2Ring = new Circle(18);
        step2Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step2Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step2Ring.setStrokeWidth(3);

        step2Number = new Label("2");
        step2Number.setStyle("-fx-text-fill: #9580FFFF; -fx-font-size: 20px;");
        step2Number.getStyleClass().addAll(Styles.TEXT_BOLD);

        StackPane step2NumberPane = new StackPane(step2Ring, step2Number);
        step2NumberPane.setAlignment(Pos.CENTER);

        step2Label = new Label("Einstellungen");
        step2Label.setStyle("-fx-text-fill: #f8f8f2; -fx-font-size: 16px;");
        step2Label.getStyleClass().addAll(Styles.TEXT_BOLD);

        VBox step2Box = new VBox(8, step2NumberPane, step2Label);
        step2Box.setAlignment(Pos.CENTER);

        // Line 2-3
        line2 = new Line(0, 18, 300, 18);
        line2.setStroke(javafx.scene.paint.Color.web("#6272a4"));
        line2.setStrokeWidth(3);

        // Step 3: Export
        step3Ring = new Circle(18);
        step3Ring.setFill(javafx.scene.paint.Color.TRANSPARENT);
        step3Ring.setStroke(javafx.scene.paint.Color.web("#9580FFFF"));
        step3Ring.setStrokeWidth(3);

        step3Number = new Label("3");
        step3Number.setStyle("-fx-text-fill: #9580FFFF; -fx-font-size: 20px;");
        step3Number.getStyleClass().addAll(Styles.TEXT_BOLD);

        StackPane step3NumberPane = new StackPane(step3Ring, step3Number);
        step3NumberPane.setAlignment(Pos.CENTER);

        step3Label = new Label("Export");
        step3Label.setStyle("-fx-text-fill: #f8f8f2; -fx-font-size: 16px;");
        step3Label.getStyleClass().addAll(Styles.TEXT_BOLD);

        VBox step3Box = new VBox(8, step3NumberPane, step3Label);
        step3Box.setAlignment(Pos.CENTER);

        // Add minimal horizontal padding between lines and circles
        HBox.setMargin(line1, new Insets(0, 8, 0, 16));
        HBox.setMargin(line2, new Insets(0, 16, 0, 8));

        stepper
            .getChildren()
            .addAll(step1Box, line1, step2Box, line2, step3Box);

        return stepper;
    }

    private void updateStepperState() {
        // Active color
        String activeRingColor = "#9580FFFF";
        String activeLabelColor = "#f8f8f2";

        // Dimmed color for inactive steps
        String dimmedRingColor = "#6272a4";
        String dimmedLabelColor = "#6272a4";

        // Active line color
        String activeLineColor = "#9580FFFF";
        // Dimmed line color
        String dimmedLineColor = "#4a5a8a";

        // Update Step 1
        if (activeStep >= 1) {
            step1Ring.setStroke(javafx.scene.paint.Color.web(activeRingColor));
            step1Number.setStyle(
                "-fx-text-fill: " + activeRingColor + "; -fx-font-size: 20px;"
            );
            step1Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step1Label.setStyle(
                "-fx-text-fill: " + activeLabelColor + "; -fx-font-size: 16px;"
            );
            step1Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        } else {
            step1Ring.setStroke(javafx.scene.paint.Color.web(dimmedRingColor));
            step1Number.setStyle(
                "-fx-text-fill: " + dimmedRingColor + "; -fx-font-size: 20px;"
            );
            step1Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step1Label.setStyle(
                "-fx-text-fill: " + dimmedLabelColor + "; -fx-font-size: 16px;"
            );
            step1Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        }

        // Update Step 2
        if (activeStep >= 2) {
            step2Ring.setStroke(javafx.scene.paint.Color.web(activeRingColor));
            step2Number.setStyle(
                "-fx-text-fill: " + activeRingColor + "; -fx-font-size: 20px;"
            );
            step2Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step2Label.setStyle(
                "-fx-text-fill: " + activeLabelColor + "; -fx-font-size: 16px;"
            );
            step2Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        } else {
            step2Ring.setStroke(javafx.scene.paint.Color.web(dimmedRingColor));
            step2Number.setStyle(
                "-fx-text-fill: " + dimmedRingColor + "; -fx-font-size: 20px;"
            );
            step2Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step2Label.setStyle(
                "-fx-text-fill: " + dimmedLabelColor + "; -fx-font-size: 16px;"
            );
            step2Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        }

        // Update Step 3
        if (activeStep >= 3) {
            step3Ring.setStroke(javafx.scene.paint.Color.web(activeRingColor));
            step3Number.setStyle(
                "-fx-text-fill: " + activeRingColor + "; -fx-font-size: 20px;"
            );
            step3Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step3Label.setStyle(
                "-fx-text-fill: " + activeLabelColor + "; -fx-font-size: 16px;"
            );
            step3Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        } else {
            step3Ring.setStroke(javafx.scene.paint.Color.web(dimmedRingColor));
            step3Number.setStyle(
                "-fx-text-fill: " + dimmedRingColor + "; -fx-font-size: 20px;"
            );
            step3Number.getStyleClass().addAll(Styles.TEXT_BOLD);
            step3Label.setStyle(
                "-fx-text-fill: " + dimmedLabelColor + "; -fx-font-size: 16px;"
            );
            step3Label.getStyleClass().addAll(Styles.TEXT_BOLD);
        }

        // Update Line 1 (between Step 1 and Step 2)
        if (activeStep >= 2) {
            line1.setStroke(javafx.scene.paint.Color.web(activeLineColor));
        } else {
            line1.setStroke(javafx.scene.paint.Color.web(dimmedLineColor));
        }

        // Update Line 2 (between Step 2 and Step 3)
        if (activeStep >= 3) {
            line2.setStroke(javafx.scene.paint.Color.web(activeLineColor));
        } else {
            line2.setStroke(javafx.scene.paint.Color.web(dimmedLineColor));
        }
    }

    public static void main(String[] args) {
        launch(args);
    }
}
